# Generated by Django 3.0.5 on 2020-10-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('published_on',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.TextField(),
        ),
    ]
