# Generated by Django 3.0.5 on 2020-10-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201013_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status_choices',
        ),
    ]
